### ISSUE TITLE
Add Crafting Orders

### ISSUE THREAD

**Issue by infekSK** [tfmonk/Accountant#12]
Unsure if it's possible to add another section for Crafting Order gains? It's currently being counted as mail.

**Comment by tfmonk** [comment]
@infekSK it's certainly possible I will just need to find the right phrase from the mail and should be able to accommodate it

**Comment by tfmonk** [comment]
@infekSK an alpha version with support for crafting orders is being added to curseforge at the moment for me to do some final validation if you want to test and let me that would be great and if it looks good should be able to push it live in the next day or two

**Comment by infekSK** [comment]
Okay thank you for the prompt update, will use the alpha version :)
