### ISSUE TITLE
Request For Splitting "Loot" Gold, If Possible

### ISSUE THREAD

**Issue by Soeroah** [tfmonk/Accountant#19]
Hi. First, I loved using this addon in Legion, always love seeing how much I make. Thank you for the resurrection.

I was wondering if it's possible to have the "Loot" gold tracking field split up into actual loot and gold rewarded from world quests? I quite like to see how much gold I get specifically from gold-rewarding world quests and dragon race purses, but it seems the addon currently just adds all gold from quests, world quests, treasures and dead mobs as one big pool. 

I expect the only reason this is the case is because it's impossible for the addon to tell those sources apart, but just in case, I thought I'd ask about it. 

As a second request, is it possible to get an option to have the /acc command open the window on the current character's page for the session, instead of the all characters session page? I'd want to see my current character's data more often when I open the ACC window than all of them together, so it feels logical to be able to tell the addon what page to open the window on by default.

Thank you!

**Comment by tfmonk** [comment]
@Soeroah  yeah they all trigger the same in-game event that I can tell that is used to track where the gold comes from so unable to break down where it comes from
