### ISSUE TITLE
Add support for WoWUp

### ISSUE THREAD

**Issue by szjunklol** [tfmonk/Accountant#2]
Would you consider hosting the source code for Accountant also on GitHub so that the addon can be updated through WoWUp?

Since the license is GNU, I setup a repo here: https://github.com/szjunklol/Accountant

Feel free to fork it and use it if you want or if you're uninterested I'll delete it.

Thank you.

**Comment by tfmonk** [comment]
@szjunklol I will take a look and get it hosted on wago.io this weekend

**Comment by szjunklol** [comment]
Thanks, that works, too.

**Comment by tfmonk** [comment]
@szjunklol you can do, its available on wago.io now https://addons.wago.io/addons/accountant
