### ISSUE TITLE
Received Errors

### ISSUE THREAD

**Issue by WildIrishBanshee** [tfmonk/Accountant#22]
Got these errors today. Thought you may want to know. Not sure if it's affecting anything or not, I'm still testing.

114x DataStore_Currencies/DataStore_Currencies.lua:601: attempt to call global 'RequestArtifactCompletionHistory' (a nil value)
[string "@DataStore_Currencies/DataStore_Currencies.lua"]:601: in function <DataStore_Currencies/DataStore_Currencies.lua:586>
[string "=[C]"]: ?
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 RegisterChatCommand = <function> defined @Accountant/Libs/AceConsole-3.0/AceConsole-3.0.lua:81
 EnableModule = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @Accountant/Libs/AceConsole-3.0/AceConsole-3.0.lua:107
 Printf = <function> defined @Accountant/Libs/AceConsole-3.0/AceConsole-3.0.lua:65
 SetDefaultModulePrototype = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 name = "DataStore_Currencies"
 IsEnabled = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 RegisterMessage = <function> defined @Accountant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 GetArgs = <function> defined @Accountant/Libs/AceConsole-3.0/AceConsole-3.0.lua:140
 Print = <function> defined @Accountant/Libs/AceConsole-3.0/AceConsole-3.0.lua:50
 Characters = <table> {
 }
 IsModule = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:464
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 ThisCharacter = <table> {
 }
 baseName = "DataStore_Currencies"
 SetEnabledState = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 OnDisable = <function> defined @DataStore_Currencies/DataStore_Currencies.lua:605
 enabledState = true
 OnEnable = <function> defined @DataStore_Currencies/DataStore_Currencies.lua:586
 RegisterEvent = <function> defined @Accountant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @Accountant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 OnInitialize = <function> defined @DataStore_Currencies/DataStore_Currencies.lua:550
 UnregisterAllEvents = <function> defined @Accountant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 SendMessage = <function> defined @Accountant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 IterateModules = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 UnregisterMessage = <function> defined @Accountant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 NewModule = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 GetName = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 UnregisterEvent = <function> defined @Accountant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Disable = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
}
_ = 6
_ = 8
arch = 10
(*temporary) = nil
(*temporary) = "attempt to call global 'RequestArtifactCompletionHistory' (a nil value)"
addon = <table> {
 SetDefaultModuleLibraries = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 RegisterChatCommand = <function> defined @Accountant/Libs/AceConsole-3.0/AceConsole-3.0.lua:81
 EnableModule = <function> defined @Accountant/Libs/AceAddon-3.0/Ace

114x AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "RESEARCH_ARTIFACT_HISTORY_READY"
[string "=[C]"]: in function `RegisterEvent'
[string "@Scrap/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Accountant/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:132: in function `RegisterEvent'
[string "@DataStore_Crafts/DataStore_Crafts.lua"]:825: in function <DataStore_Crafts/DataStore_Crafts.lua:814>
[string "=[C]"]: ?
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
(*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "RESEARCH_ARTIFACT_HISTORY_READY"

**Comment by tfmonk** [comment]
@WildIrishBanshee Based on the errors its not an issue with the Accountant addon, maybe just a case of false reporting, 

I beleive the actual cause is the DataStore_Currencies addon
