### ISSUE TITLE
Duplicate File Load Detected

### ISSUE THREAD

**Issue by passivecore** [tfmonk/Accountant#23]
A week ago, after updating the addon, it started showing this lua error.

![Ekran görüntüsü 2024-05-09 105903](https://github.com/tfmonk/Accountant/assets/123672038/a6115b5e-28a5-4b49-b534-e1b976890bf2)
![Ekran görüntüsü 2024-05-09 112706](https://github.com/tfmonk/Accountant/assets/123672038/379d3df4-66af-4d64-8d0c-40b67a170e6b)
![Ekran görüntüsü 2024-05-09 112743](https://github.com/tfmonk/Accountant/assets/123672038/8a1e7645-cd18-4eec-b873-20555e618ace)

**Comment by roweysvn** [comment]
Also getting the same error, mine says 

24x Accountant/Accountant.toc:27 Duplicate File Load Detected. [Accountant/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.xml] first loaded at [Accountant/Libs/AceConfig-3.0/AceConfig-3.0.xml:5]

**Comment by zamtin2021** [comment]
Same issue on my end 

![image](https://github.com/tfmonk/Accountant/assets/83191591/7df5bd47-a74f-4238-bf83-387deb3030ec)

**Comment by Sinnrg** [comment]
for temp solution edit Accountant.toc line 27 
Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.xml
change to 
## Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.xml
