### ISSUE TITLE
Receiving a bug in 11.0.2 when trying to open the options.

### ISSUE THREAD

**Issue by wayneluke** [tfmonk/Accountant#26]
Latest version installed.

4x Accountant/Accountant.lua:693: attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)
[string "@Accountant/Accountant.lua"]:693: in function `OnClick'
[string "@SilverDragon/lib/LibDBIcon-1.0-54/LibDBIcon-1.0.lua"]:179: in function <...Ons/SilverDragon/lib/LibDBIcon-1.0/LibDBIcon-1.0.lua:177>

Locals:
_ = LibDBIcon10_Accountant {
 fadeOut = AnimationGroup {
 }
 dataObject = <table> {
 }
 isMouseDown = false
 db = <table> {
 }
 icon = Texture {
 }
}
button = "RightButton"
(*temporary) = nil
(*temporary) = Frame {
 obj = <table> {
 }
 name = "Accountant"
}
(*temporary) = "attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)"
SC = <table> {
 artwork_path = "Interface\AddOns\Accountant\Artwork\"
 repair_cost = 0
 modules = <table> {
 }
 current_money = 5922164218
 current_tab = 5
 AllDropdown = "All Chars"
 Realm = "Wyrmrest Accord"
 ShowAlliance = true
 got_name = true
 could_repair = false
 data = <table> {
 }
 DIVIDER = "-"
 AUTHOR = "tfmonk "
 defaultModuleState = true
 db = <table> {
 }
 baseName = "Accountant"
 Toons = <table> {
 }
 GOLD_COLOR = "|cFFFFFF00"
 can_repair = ""
 GREEN_COLOR = "|cff19ff19"
 DEV = true
 repair_money = 0
 ShowHorde = true
 enabledState = true
 verbose = false
 show_setup = false
 Char = "Tiannah"
 Version = "10.2.7"
 player = "Wyrmrest Accord-Tiannah"
 AllCharsMaxRows = 60
 log_modes_short = <table> {
 }
 last_money = 5922164218
 defaultModuleLibraries = <table> {
 }
 refund_mode = ""
 TITLE = "Accountant"
 name = "Accountant"
 Faction = "Alliance"
 orderedModules = <table> {
 }
 CREDAUTHOR = "Urnati & Dajin & Thorismud"
 show_mode = false
 AllToons = <table> {
 }
 mode = ""
 MaxRows = 15
 sender = ""
 LDBIcon = <table> {
 }
 show_events = false
 log_modes = <table> {
 }
 show_toons = "All Chars"
}

**Comment by wayneluke** [comment]
I don't have Silverdragon installed so I don't know why your addon is trying to call it.

**Comment by scottnixon** [comment]
I also get an error when trying to open options....looks to be similar to OP.

Date: 2024-07-30 16:56:38
ID: 6
Error occured in: Global
Count: 1
Message: Interface/AddOns/Accountant/Accountant.lua line 693:
   attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)
Debug:
   [string "@Interface/AddOns/Accountant/Accountant.lua"]:693: OnClick()
   [string "@Interface/AddOns/Masque/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:179:
      ...e/AddOns/Masque/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:177
Locals:
_ = LibDBIcon10_Accountant {
 fadeOut = AnimationGroup {
 }
 dataObject = <table> {
 }
 isMouseDown = false
 db = <table> {
 }
 icon = Texture {
 }
}
button = "RightButton"
(*temporary) = nil
(*temporary) = Frame {
 obj = <table> {
 }
 name = "Accountant"
}
(*temporary) = "attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)"
SC = <table> {
 artwork_path = "Interface\AddOns\Accountant\Artwork\"
 repair_cost = 0
 modules = <table> {
 }
 current_money = 7714542167
 current_tab = 4
 AllDropdown = "All Chars"
 Realm = "Baelgun"
 ShowAlliance = true
 got_name = true
 could_repair = false
 data = <table> {
 }
 DIVIDER = "-"
 AUTHOR = "tfmonk "
 defaultModuleState = true
 db = <table> {
 }
 baseName = "Accountant"
 Toons = <table> {
 }
 GOLD_COLOR = "|cFFFFFF00"
 can_repair = ""
 GREEN_COLOR = "|cff19ff19"
 DEV = true
 repair_money = 0
 ShowHorde = true
 enabledState = true
 verbose = false
 show_setup = false
 Char = "Talongore"
 Version = "10.2.7"
 player = "Baelgun-Talongore"
 AllCharsMaxRows = 60
 log_modes_short = <table> {
 }
 last_money = 7714542167
 defaultModuleLibraries = <table> {
 }
 refund_mode = ""
 TITLE = "Accountant"
 name = "Accountant"
 Faction = "Alliance"
 orderedModules = <table> {
 }
 CREDAUTHOR = "Urnati & Dajin & Thorismud"
 show_mode = false
 AllToons = <table> {
 }
 mode = ""
 MaxRows = 15
 sender = ""
 LDBIcon = <table> {
 }
 show_events = false
 log_modes = <table> {
 }
 show_toons = "All Chars"
}

**Comment by tfmonk** [comment]
I'm currently testing a fix for this, should hopefully be available soon
