### ISSUE TITLE
Gold in Warband bank

### ISSUE THREAD

**Issue by jparac** [tfmonk/Accountant#27]
**Is your feature request related to a problem? Please describe.**
With release of The War Within players are now able to deposit gold inside warband bank. There are couple of issues in addon atm
1. The gold in warband bank is not being tracked inside the addon
2. Depositing gold inside warband bank is being logged as expenditure

**Describe the solution you'd like**
1. Add additional display of gold in warband bank
2. Stop logging gold deposit inside warband bank as expenditure

**Comment by tfmonk** [comment]
@jparac I'll take a look at it, I have some ideas but I think I might be able to do a half way house.

There is no specific event triggered to track deposits to the warband bank, There is the bank opening/closing one that could be used but that would also cover bank tab purchases.

If we left the deposits as expenditures and withdrawing as revenue, so we could track bank tab purchases.... i think i could add a separate bank category that would track it and be able to add something that shows your warband bank total gold and add it to the total gold amount so the figure stays accurate.

There might be a way when i retrieve the values to basically do something like ((bank in + bank in) - warband bank) = expense/revenue but would need to figure that bit out

**Comment by tfmonk** [comment]
@jparac How would this look to you its a work in progress.

![image](https://github.com/user-attachments/assets/36981352-bfb6-4b3e-9afb-a2d098c8399b)

I'm having a bit of trouble figuring out the right logic to make it not show warband deposits and withdrawls as expenditure or revenue while trying to track tab purchases.

**Comment by jhammersholt** [comment]
It seems there's a slight bug in this as it accumulates the warband gold for each character

**Comment by tfmonk** [comment]
I will double check this when I'm online later on.
