### ISSUE TITLE
error in patch 10.0

### ISSUE THREAD

**Issue by Daeveren** [tfmonk/Accountant#3]
**Describe the bug**
error shown at login

v 9.2.7.0.0

> 4x Interface/SharedXML/SharedUIPanelTemplates.lua:619: attempt to index field 'Left' (a nil value)
> [string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:619: in function `PanelTemplates_SelectTab'
> [string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:484: in function `PanelTemplates_UpdateTabs'
> [string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:465: in function `PanelTemplates_SetTab'
> [string "@Interface/AddOns/Accountant/Accountant.lua"]:2145: in function `ShowValues'
> [string "@Interface/AddOns/Accountant/Accountant.lua"]:2152: in function `OnShow'
> [string "*Accountant.xml:573_OnShow"]:1: in function <[string "*Accountant.xml:573_OnShow"]:1>
> [string "=[C]"]: in function `Show'
> [string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
> [string "@Interface/FrameXML/UIParent.lua"]:2687: in function `ShowUIPanel'
> [string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
> [string "=[C]"]: in function `SetAttribute'
> [string "@Interface/FrameXML/UIParent.lua"]:3150: in function `ShowUIPanel'
> [string "@Interface/AddOns/Accountant/Accountant.lua"]:716: in function `LeftButton_OnClick'
> [string "@Interface/AddOns/Accountant/Accountant.lua"]:671: in function `OnClick'
> [string "@Interface/AddOns/ChocolateBar/Chocolate.lua"]:298: in function <Interface/AddOns/ChocolateBar/Chocolate.lua:295>
> 
> Locals:
> tab = AccountantFrameTab1 {
> 
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "attempt to index field 'Left' (a nil value)"

**Comment by tfmonk** [comment]
This should be fixed in the newest version which should be available once its approved on curse.
