### ISSUE TITLE
Warband Bank counted multiple times in Total Gold

### ISSUE THREAD

**Issue by ZehelFenris** [tfmonk/Accountant#33]
**Describe the bug**
Counts warband bank for all characters in the total gold so if I have 15 chars like in the screenshot then it adds the warband bank 15 times to the total gold

**Expected behavior**
Only count warband bank once in total gold

**Screenshots**
![image_2024-08-23_120032234](https://github.com/user-attachments/assets/2d675639-22ec-47b2-9dc4-2aab7942eb7c)

**Addon version (please complete the following information):**
 - Version 11.0.0

**Comment by tfmonk** [comment]
I accidentally pushed the version with the bug and not the fixed one that i was using, the new version will be available shortly
