### ISSUE TITLE
AH profit goes to mail section

### ISSUE THREAD

**Issue by razorbladehnt** [tfmonk/Accountant#6]
On RU client every profit from AH goes to mail section instead of AH

Steps to recreate
1 install ru locale for Wow
2 connect to ru realm
3 sell something on AH
4 loot mailbox

Screen from RU client
![123](https://user-images.githubusercontent.com/15623755/200496257-fb0360bc-ac53-41cd-9892-ee792403ee14.png)

And this is a screen from EU client (expected behaviour) 
![eu](https://user-images.githubusercontent.com/15623755/200497232-5bde8885-dd58-4621-a31f-b9101b2d6a26.png)

 - Version 10.0.0.0.0

**Comment by tfmonk** [comment]
its, possible an issue with localisation in regards to the mail names for auction house emails being different between the languages on EU/US clients its looking for the mail string "Auction successful:" or "Outbid" to determine if its an auction mail to allocate the gold to the right category but in Russian it is something different..

To fix it would need help creating an Russian locale file and translating the string

**Comment by razorbladehnt** [comment]
"Auction successful:" will be "Аукцион состоялся:"
Not sure how "Outbid:" will be translated
I made some bids if any of them will be outbided i'll add correct translation here

**Comment by tfmonk** [comment]
Thanks, I will look at adding some additional localization files for the various locales available for wow, which will allow strings within Accountant to start being translated so functionality will work

**Comment by razorbladehnt** [comment]
Outbid in RU locale
Выша ставка перебита (предмет: %itemname%)

**Comment by tfmonk** [comment]
@razorbladehnt thanks there should be an alpha version going up on curse shortly with localization enabled which should hopefully fix the issue.

**Comment by razorbladehnt** [comment]
![oof](https://user-images.githubusercontent.com/15623755/200908962-42fc40d5-d65d-4359-8fe9-5434ed82ce9f.png)
A bit broken after update =)
https://pastebin.com/HyGk98ZS with these changes it works like expected but look a little bit funky
![Безымянный](https://user-images.githubusercontent.com/15623755/200911139-2968af4f-4f07-48dd-bbf6-7282b567b1c9.png)
I'll try to translate the rest after the raid

**Comment by tfmonk** [comment]
its due to UnitFactionGroup API returning English for the faction name, I did do some testing bu looks like the languages i used didn't have this converted, I've tried Russian and its now working again.

I've pushed a fix out which should be available shortly
